language: python
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      language: shell      
    # - os: linux
    #   dist: xenial
python:
  - 3.6
  - 3.7
cache: pip
install:
  - pip3 install tox-travis
script:
  tox -v
before_deploy:
  - pip3 install twine
deploy:
  provider: pypi
  user: bbp.opensource
  password:
    secure: N/2AGpTUSOGOxQqYulja5Etj228w1SByVuX+ozPvuPJTm5kJh5fqav8FVtPLziaWAaWxJ6W2nFdWT9AwodwMk3+1NBHMWpOZ3NJnvibz0cvYCkXdNcgXOFGrPSeX3Oo2d74IeT20R44lieZEW62j4488SSaVkwr3p7YgyfVMVGo=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
